kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-discovery-client
rules:
- apiGroups: 
  - "" # "" indicates the core API group
  resources: 
  - services
  - pods
  - configmaps
  - endpoints
  verbs: 
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default:service-discovery-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-discovery-client
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace}}
