kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "beschriftung.fullname" . }}-service-discovery
  labels:
    {{- include "beschriftung.labels" . | nindent 4 }}
rules:
- apiGroups: 
  - "" # "" indicates the core API group
  resources: 
  - services
  - pods
  - configmaps
  - endpoints
  verbs: 
  - get
  - watch
  - list