apiVersion: v1
kind: Service
metadata:
  name: {{ template "beschriftung.fullname" . }}
  labels:
    {{- include "beschriftung.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  ipFamilyPolicy: PreferDualStack
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "beschriftung.selectorLabels" . | nindent 4 }}
