# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker.berg-turbenthal.ch/beschriftung
  # override version if needed
  # tag: 20230325-083854
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  managementPort: 9080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 400m
    memory: 512Mi
ingress:
  enabled: false
  hostname: beschriftung.lkw.teamkoenig.ch
  className: nginx
  certificate:
    enabled: false
    clusterIssuer: letsencrypt-prod
    duration: 2160h0m0s
    renewBefore: 360h0m0s